export const authShell = {
  page: 'min-h-screen w-full bg-canvas text-[#1A1510] font-sans',
  ruled: 'bg-[repeating-linear-gradient(to_bottom,transparent,transparent_47px,rgba(26,21,16,0.028)_47px,rgba(26,21,16,0.028)_48px)]',
  shellWrap: 'flex min-h-screen w-full items-center justify-center p-6',
  shell: 'relative z-[1] flex w-full max-w-shell overflow-hidden rounded-clausule2 border border-[rgba(26,21,16,0.18)] max-sm:flex-col',
  darkPanel: 'flex w-[268px] shrink-0 flex-col justify-between bg-nav px-7 py-8 max-sm:hidden',
  lightPanel: 'flex min-w-0 flex-1 flex-col bg-[#FDFCFA] px-shell-x py-shell-y max-sm:px-5 max-sm:py-8',
  narrow: 'mx-auto flex w-full max-w-auth flex-col',
  stepLayout: 'grid gap-8 lg:grid-cols-[minmax(0,1fr)_280px]',
  brandRow: 'flex items-center gap-[9px]',
  brandBug: 'flex h-7 w-7 shrink-0 items-center justify-center rounded-[8px] bg-acc',
  brandTextDark: 'text-[15px] font-extrabold text-[#FBF7F2]',
  brandTextLight: 'text-[15px] font-extrabold tracking-[-0.3px] text-[#1A1510]',
  leftBody: 'flex flex-col gap-3',
  headline: 'm-0 text-[26px] font-black leading-[1.15] tracking-[-0.8px] text-[#FBF7F2]',
  headlineSub: 'm-0 text-[13px] leading-[1.7] text-[#B8B2AC]',
  footer: 'text-[11px] text-[#786B5F]',
  signinNote: 'mt-5 text-center text-[11px] leading-[1.6] text-[#786B5F]',
  signinLink: 'font-semibold text-[#3D3228]',
  topbar: 'relative z-10 flex items-center justify-between border-b border-[rgba(26,21,16,0.1)] px-12 py-[18px] max-sm:px-5',
  topbarBrand: 'flex items-center gap-[9px]',
  topbarBug: 'flex h-7 w-7 items-center justify-center rounded-[8px] bg-[#1A1510]',
  main: 'relative z-10 flex flex-1 items-start justify-center px-6 py-10 max-sm:px-5',
}

export const signupUi = {
  heading: 'mb-2 text-[28px] font-black leading-[1.05] tracking-[-1px] text-[#1A1510] max-sm:text-[24px]',
  sub: 'mb-6 text-[13px] leading-[1.7] text-[#5B4E42]',
  label: 'mb-[7px] block text-label font-bold uppercase text-[#786B5F]',
  input: 'block min-w-0 w-full rounded-clausule border-[1.5px] border-[rgba(26,21,16,0.12)] bg-transparent px-field-x py-field-y text-field font-medium text-[#1A1510] outline-none transition-[border-color,box-shadow,background-color] duration-150 placeholder:text-[#786B5F] focus:border-[#2A221A] focus:shadow-[0_0_0_3px_rgba(60,45,35,0.08)]',
  inputLocked: 'cursor-default bg-[rgba(26,21,16,0.04)] text-[#5B4E42]',
  inputError: 'border-red focus:border-red focus:shadow-[0_0_0_3px_rgba(184,50,50,0.12)]',
  hint: 'mt-2 block text-helper text-[#786B5F]',
  hintError: 'text-red',
  hintWarn: 'text-[#8F5E16]',
  suggestion: 'font-semibold text-[#3D3228] underline decoration-[rgba(61,50,40,0.28)] underline-offset-2',
  nameRow: 'grid gap-3 sm:grid-cols-2',
  field: 'mb-5',
  terms: 'mb-5 mt-5 grid gap-2',
  termsLabel: 'flex items-start gap-3 text-helper leading-[1.6] text-[#5B4E42]',
  checkbox: 'mt-0.5 h-4 w-4 shrink-0 accent-acc',
  termsError: 'text-helper font-semibold text-red',
  cta: 'inline-flex w-full items-center justify-center gap-2 rounded-clausule border-none bg-acc px-4 py-3 text-[14px] font-bold text-[#FAF7F3] transition-opacity duration-150 hover:opacity-90 disabled:cursor-default disabled:opacity-50',
  ctaTerra: 'bg-[#8F371F]',
  back: 'mt-3 inline-flex items-center gap-2 text-[13px] font-semibold text-[#5B4E42] transition-colors duration-150 hover:text-[#1A1510]',
  ssoDivider: 'my-5 flex items-center gap-3',
  ssoDividerLine: 'h-px flex-1 bg-[rgba(26,21,16,0.1)]',
  ssoDividerText: 'text-[11px] font-bold uppercase tracking-[0.08em] text-[#786B5F]',
  ssoButton: 'mb-3 flex w-full items-center gap-3 rounded-clausule border border-[rgba(26,21,16,0.12)] bg-white px-4 py-3 text-left transition-[border-color,transform] duration-150 hover:border-[rgba(26,21,16,0.24)] hover:-translate-y-px',
  ssoLogo: 'flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[rgba(26,21,16,0.04)]',
  ssoLabel: 'flex-1 text-[14px] font-bold text-[#1A1510]',
  ssoArrow: 'text-[#786B5F]',
  progressWrap: 'relative z-10 border-b border-[rgba(26,21,16,0.1)] px-6 py-5 max-sm:px-5',
  progressInner: 'mx-auto flex w-full items-center max-w-prose',
  progressTrack: 'flex flex-1 items-center',
  progressItem: 'flex items-center gap-3',
  progressCircle: 'flex h-8 w-8 items-center justify-center rounded-full border border-[rgba(26,21,16,0.14)] bg-[#FDFCFA] text-[12px] font-extrabold text-[#786B5F]',
  progressCircleActive: 'border-[#2A221A] bg-[#2A221A] text-[#FDFCFA]',
  progressCircleDone: 'border-acc bg-acc text-[#FDFCFA]',
  progressLabel: 'text-[12px] font-semibold text-[#786B5F]',
  progressLabelDone: 'text-[#3D3228]',
  progressLabelActive: 'text-[#1A1510]',
  progressConnector: 'mx-3 h-px flex-1 bg-[rgba(26,21,16,0.1)]',
  progressConnectorDone: 'bg-acc',
  asideWrap: 'grid gap-4',
  asideCard: 'rounded-clausule2 border border-[rgba(26,21,16,0.1)] bg-white/80 p-5 backdrop-blur-[2px]',
  asideLabel: 'mb-2 text-label font-bold uppercase text-[#786B5F]',
  asidePrice: 'text-[34px] font-black leading-none tracking-[-1px] text-[#1A1510]',
  asidePricePeriod: 'ml-1 text-[16px] font-bold text-[#5B4E42]',
  asidePriceNote: 'mt-2 text-helper text-[#786B5F]',
  asideList: 'grid gap-3',
  asideFeature: 'flex gap-3 text-[13px] leading-[1.65] text-[#3D3228]',
  asideDot: 'mt-[7px] h-2 w-2 shrink-0 rounded-full bg-acc',
  orderSummary: 'mb-5 rounded-clausule2 border border-[rgba(26,21,16,0.1)] bg-white/80 p-5',
  orderLabel: 'mb-3 text-label font-bold uppercase text-[#786B5F]',
  orderRow: 'flex items-center justify-between gap-4 text-[14px]',
  orderItem: 'font-medium text-[#3D3228]',
  orderValue: 'font-bold text-[#1A1510]',
  orderDivider: 'my-4 h-px bg-[rgba(26,21,16,0.1)]',
  orderTotalLabel: 'text-[13px] font-bold text-[#3D3228]',
  orderTotalValue: 'text-[18px] font-black text-[#1A1510]',
  payField: 'mb-5',
  cardWrap: 'relative',
  cardIcons: 'pointer-events-none absolute inset-y-0 right-3 flex items-center gap-2',
  cardIcon: 'flex h-7 w-7 items-center justify-center rounded-md bg-white',
  expiryRow: 'mb-5 grid gap-3 sm:grid-cols-2',
  secureNote: 'mb-5 flex items-center gap-2 rounded-clausule bg-[rgba(208,90,52,0.08)] px-3 py-2 text-helper text-[#5B4E42]',
  apiError: 'mb-5 rounded-clausule bg-red-bg px-3 py-2 text-helper font-semibold text-red',
  trialNote: 'mt-4 text-center text-helper text-[#786B5F]',
  successRing: 'mb-6 flex h-[72px] w-[72px] items-center justify-center rounded-full bg-acc shadow-[0_18px_40px_rgba(208,90,52,0.18)]',
  doneSub: 'max-w-[36rem]',
  includes: 'mb-6 rounded-clausule2 border border-[rgba(26,21,16,0.1)] bg-white/80 p-5',
  includesLabel: 'mb-3 text-label font-bold uppercase text-[#786B5F]',
  includesList: 'grid gap-3',
  includeItem: 'flex gap-3 text-[13px] leading-[1.65] text-[#3D3228]',
  checkCircle: 'flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-acc text-[#FAF7F3]',
  questions: 'mt-4 text-center text-helper text-[#786B5F]',
}
