export const mfaUi = {
  setupWrap: 'flex min-h-screen items-center justify-center bg-canvas px-4 py-10',
  setupCard: 'w-full max-w-prose rounded-clausule2 border border-rule-em bg-card p-6 shadow-float',
  pane: 'mx-auto grid w-full max-w-[34rem] gap-5',
  paneCenter: 'items-center text-center',
  heading: 'text-[30px] font-black leading-[1.05] tracking-[-1px] text-tp max-sm:text-[26px]',
  sub: 'text-[15px] leading-[1.7] text-tm',
  progress: 'mb-6 flex gap-2',
  progressSeg: 'h-2 flex-1 rounded-full bg-[rgba(60,45,35,0.1)]',
  progressSegActive: 'bg-acc',
  progressSegDone: 'bg-[#2F6F5E]',
  iconWrap: 'mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-acc/10 text-acc',
  resend: 'text-center text-helper text-tm',
  resendBtn: 'font-semibold text-acc underline decoration-[rgba(127,53,31,0.28)] underline-offset-2',
  error: 'text-helper font-semibold text-red',
  otpRow: 'flex items-center justify-center gap-2',
  otpRowError: 'rounded-clausule bg-red-bg/60 p-2',
  otpRowDone: 'rounded-clausule bg-[rgba(47,111,94,0.08)] p-2',
  otpBox: 'h-12 w-11 rounded-clausule border-[1.5px] border-rule-em bg-canvas text-center text-[22px] font-black text-tp outline-none transition-[border-color,box-shadow] duration-150 focus:border-acc focus:shadow-[0_0_0_3px_rgba(127,53,31,0.12)] disabled:cursor-default disabled:opacity-60',
  card: 'rounded-clausule2 border border-rule-em bg-bg-comp p-5',
  buttonPrimary: 'inline-flex items-center justify-center gap-2 rounded-clausule border-none bg-acc px-4 py-3 text-[14px] font-bold text-[#FAF7F3] transition-opacity duration-150 hover:opacity-90 disabled:cursor-default disabled:opacity-50',
  buttonGhost: 'inline-flex items-center gap-2 self-start text-[13px] font-semibold text-tm transition-colors duration-150 hover:text-tp',
  appShell: 'grid min-h-screen bg-canvas lg:grid-cols-[minmax(320px,1fr)_minmax(0,32rem)]',
  appLeft: 'flex flex-col justify-between bg-nav px-8 py-10 text-[#FBF7F2] max-lg:hidden',
  appRight: 'flex min-h-screen flex-col justify-center px-6 py-10 max-sm:px-5',
  logo: 'flex items-center gap-[9px]',
  logoBug: 'flex h-7 w-7 items-center justify-center rounded-[8px] bg-acc text-[#FBF7F2]',
  logoNameLight: 'text-[15px] font-extrabold text-[#FBF7F2]',
  leftBody: 'flex flex-col gap-4',
  leftHeadline: 'text-[34px] font-black leading-[1.02] tracking-[-1.1px]',
  leftCopy: 'max-w-[28rem] text-[14px] leading-[1.7] text-[#B8B2AC]',
  steps: 'grid gap-3',
  stepRow: 'flex items-center gap-3 text-[13px] text-[#D8CEC1]',
  stepNum: 'flex h-7 w-7 items-center justify-center rounded-full border border-[rgba(255,255,255,0.14)]',
  stepNumActive: 'border-[#F8D37B] bg-[#F8D37B] text-nav',
  stepNumDone: 'border-[#2F6F5E] bg-[#2F6F5E] text-[#F5F0EA]',
  title: 'mt-6 text-[28px] font-black tracking-[-0.8px] text-tp',
  body: 'mt-3 text-[15px] leading-[1.7] text-tm',
  preview: 'mt-6 rounded-clausule2 border border-rule-em bg-card p-5 shadow-float',
  previewHead: 'flex items-start gap-3',
  previewIcon: 'mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-acc/10 text-acc',
  previewMeta: 'min-w-0 flex-1',
  previewFrom: 'text-[13px] font-bold text-tp',
  previewSubject: 'text-helper text-tm',
  previewTime: 'text-[11px] font-medium uppercase tracking-[0.08em] text-tm',
  codeBlock: 'mt-4 flex items-center gap-2 rounded-clausule bg-canvas px-4 py-3',
  codeDigit: 'flex h-10 w-8 items-center justify-center rounded-[8px] border border-rule bg-white text-[20px] font-black text-tp',
  codeSeparator: 'h-1.5 w-1.5 rounded-full bg-tm',
  metaRow: 'mt-5 flex items-center justify-between gap-3 text-helper text-tm',
  expired: 'font-bold text-red',
  footer: 'mt-5 grid gap-2 text-helper text-tm',
  trustStrip: 'mt-6 flex flex-wrap items-center gap-3 text-helper text-tm',
  trustItem: 'inline-flex items-center gap-2',
  dividerDot: 'h-1 w-1 rounded-full bg-rule-em',
  securityRow: 'mb-5 flex items-center gap-3 rounded-clausule border border-rule-em bg-bg-comp px-4 py-3',
  securityIcon: 'flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-acc/10 text-acc',
  factorCard: 'rounded-clausule2 border border-rule-em bg-card p-5',
  factorCardDone: 'border-[rgba(47,111,94,0.2)] bg-[rgba(47,111,94,0.06)]',
  factorHead: 'flex items-start gap-4',
  factorBadge: 'flex h-8 w-8 items-center justify-center rounded-full bg-acc text-[13px] font-black text-[#FAF7F3]',
  factorBadgeDone: 'bg-[#2F6F5E]',
  factorTitle: 'text-[16px] font-black text-tp',
  factorSub: 'mt-1 text-helper text-tm',
  factorBody: 'mt-5 grid gap-4',
  factorInstruction: 'text-[13px] leading-[1.65] text-tm',
  qrWrap: 'flex justify-center rounded-clausule2 border border-rule-em bg-[#FAF7F3] p-4',
  secretRow: 'flex items-center gap-3 rounded-clausule bg-canvas px-4 py-3',
  secret: 'min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap text-[13px] font-bold tracking-[0.14em] text-tp',
  copyBtn: 'flex h-10 w-10 items-center justify-center rounded-clausule border border-rule-em bg-card text-tm transition-colors duration-150 hover:text-tp',
  factorActions: 'mt-5',
  successRing: 'mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#2F6F5E] text-[#F5F0EA] shadow-[0_16px_36px_rgba(47,111,94,0.2)]',
}
