export const bragShell = {
  page: 'be-page flex min-h-screen w-full bg-canvas',
  rail: 'be-rail be-sidebar sticky top-0 flex h-screen w-[46px] shrink-0 flex-col items-center bg-nav px-0 py-[18px] max-sm:fixed max-sm:bottom-0 max-sm:left-0 max-sm:right-0 max-sm:z-[100] max-sm:h-[56px] max-sm:w-full max-sm:flex-row max-sm:justify-around max-sm:border-t max-sm:border-r-0 max-sm:px-2 max-sm:py-0',
  railLogo: 'be-rail-logo mb-5 block h-7 w-7 rounded-[7px] max-sm:hidden',
  railNav: 'be-rail-nav flex flex-1 flex-col items-center gap-1 max-sm:w-full max-sm:flex-none max-sm:flex-row max-sm:justify-around max-sm:gap-0',
  railBtn: 'be-rail-btn flex h-[34px] w-[34px] items-center justify-center rounded-[var(--r)] text-[var(--be-rail-icon)] transition-colors duration-150 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[#F8D37B] max-sm:h-11 max-sm:w-11',
  railBtnActive: 'be-rail-btn-active bg-[var(--be-rail-active-bg)] text-[var(--be-rail-icon-hover)]',
  railFoot: 'be-rail-foot flex flex-col items-center gap-2 max-sm:hidden',
  railIconBtn: 'be-rail-icon-btn flex h-7 w-7 items-center justify-center text-[var(--be-rail-icon)] transition-colors duration-150 hover:text-[var(--be-rail-icon-hover)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[#F8D37B]',
  main: 'be-main min-w-0 flex-1',
  inner: 'be-inner mx-auto flex w-full max-w-prose flex-col px-8 py-10 max-sm:px-4 max-sm:pb-[88px] max-sm:pt-6',
  identity: 'be-identity be-sidebar hidden w-[240px] shrink-0 overflow-y-auto border-r border-[var(--be-identity-rule)] bg-[radial-gradient(circle_at_92%_8%,rgba(248,211,123,0.12),transparent_26%),linear-gradient(180deg,var(--be-identity-surface)_0%,var(--be-identity-surface-strong)_100%)] text-[#2A221A] md:flex',
  sidebarHeader: 'be-sidebar-header border-b border-rule px-5 pb-[17px] pt-[21px]',
  sidebarEyebrow: 'be-sidebar-eyebrow text-[9px] font-bold uppercase tracking-[4px] text-[var(--acc-text)]',
  sidebarBody: 'be-sidebar-body flex flex-1 flex-col gap-5 p-5',
  sidebarAvatar: 'be-sidebar-avatar be-avatar-pop flex h-[84px] w-[84px] items-center justify-center rounded-[26px] bg-[#2A221A] text-[26px] font-black text-[#FAF7F3]',
  sidebarName: 'be-sidebar-name mt-4 text-[24px] font-black tracking-[-0.8px] text-[#241D16]',
  sidebarRole: 'be-sidebar-role mt-1 text-[13px] leading-[1.6] text-[#6D5F53]',
  divider: 'be-divider h-px bg-rule',
  notesLabel: 'be-notes-label text-label font-bold uppercase text-[var(--acc-text)]',
  noteQuote: 'be-note-quote mt-2 text-[14px] leading-[1.75] text-[#2A221A]',
  overviewLabel: 'be-overview-label text-label font-bold uppercase text-[var(--acc-text)]',
  strengthRow: 'be-strength-row mt-3 flex items-center gap-4',
  rings: 'be-sidebar-rings relative h-[50px] w-[50px] shrink-0',
  ringsOverlay: 'be-sidebar-rings-overlay absolute inset-0',
  status: 'be-overview-status text-[16px] font-black text-[#241D16]',
  statusSub: 'be-overview-sub mt-1 text-helper text-[#6D5F53]',
  ringLegend: 'be-ring-legend mt-4 grid gap-2 text-[12px] text-[#4D4035]',
  ringItem: 'be-ring-leg flex items-center gap-2',
  ringItemMissing: 'be-ring-leg--missing opacity-75',
  ringDot: 'be-ring-leg-dot h-2.5 w-2.5 shrink-0 rounded-full',
  ringDotMissing: 'be-ring-leg-dot--missing ring-1 ring-inset ring-[rgba(60,45,35,0.18)]',
}

export const bragSettingsUi = {
  heading: 'bss-heading text-[28px] font-black tracking-[-1px] text-tp',
  subheading: 'bss-subheading mt-2 text-[14px] leading-[1.7] text-tm',
  divider: 'bss-divider mt-5 h-px bg-border',
  sectionLabel: 'bss-section-label mb-3 mt-6 text-label font-bold uppercase text-tm',
  card: 'bss-card rounded-clausule2 border border-rule-em bg-card p-5',
  mfaRow: 'bss-mfa-row flex items-start gap-4',
  mfaDivider: 'bss-mfa-divider my-5 h-px bg-border',
  mfaIcon: 'bss-mfa-icon flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-rule-em bg-canvas text-tm',
  mfaIconOn: 'bss-mfa-icon--on border-[rgba(47,111,94,0.18)] bg-[rgba(47,111,94,0.08)] text-[#2F6F5E]',
  mfaInfo: 'bss-mfa-info min-w-0 flex-1',
  mfaTitle: 'bss-mfa-title text-[15px] font-black text-tp',
  mfaSub: 'bss-mfa-sub mt-1 text-helper leading-[1.65] text-tm',
  statusOn: 'bss-mfa-status bss-mfa-status--on rounded-full bg-[rgba(47,111,94,0.1)] px-3 py-1 text-[11px] font-bold uppercase tracking-[0.08em] text-[#2F6F5E]',
  reconfigBtn: 'bss-mfa-reconfig-btn rounded-clausule border border-rule-em px-3 py-2 text-[13px] font-bold text-tp transition-colors duration-150 hover:border-tp',
  loadingState: 'bss-loading-state mt-4 flex items-center gap-2 text-helper text-tm',
  loadingDot: 'bss-loading-state__dot h-2 w-2 rounded-full bg-acc',
  totpEmpty: 'bss-totp-empty mt-4 rounded-clausule border border-rule-em bg-canvas p-4',
  totpEmptyRequired: 'bss-totp-empty--required border-[rgba(127,53,31,0.2)] bg-[rgba(127,53,31,0.06)]',
  totpTitle: 'bss-totp-empty-title text-[14px] font-black text-tp',
  totpCopy: 'bss-totp-empty-copy mt-1 text-helper leading-[1.65] text-tm',
  remindersHead: 'bss-reminder-head flex flex-wrap items-start justify-between gap-3',
  remindersTitle: 'bss-reminder-title text-[16px] font-black text-tp',
  remindersDesc: 'bss-reminder-desc mt-1 text-helper text-tm',
  remindersSummary: 'bss-reminder-summary rounded-full bg-canvas px-3 py-1 text-[11px] font-bold uppercase tracking-[0.08em] text-tm',
  reminderGroup: 'bss-reminder-group mt-5 grid gap-3',
  reminderLegend: 'bss-reminder-legend text-label font-bold uppercase text-tm',
  reminderGrid: 'bss-reminder-grid grid gap-3 sm:grid-cols-2',
  reminderOption: 'bss-reminder-option relative block rounded-clausule border border-rule-em bg-canvas p-4',
  reminderOptionActive: 'bss-reminder-option--active border-acc-border bg-acc-bg',
  reminderInput: 'bss-reminder-input absolute right-4 top-4 accent-acc',
  reminderOptionBody: 'bss-reminder-option-body block pr-7',
  reminderOptionTitle: 'bss-reminder-option-title block text-[14px] font-bold text-tp',
  reminderOptionDesc: 'bss-reminder-option-desc mt-1 block text-helper leading-[1.6] text-tm',
  frequencyGrid: 'bss-frequency-grid grid gap-2 sm:grid-cols-2',
  frequencyOption: 'bss-frequency-option relative flex items-center rounded-clausule border border-rule-em bg-canvas px-4 py-3',
  frequencyOptionActive: 'bss-frequency-option--active border-acc-border bg-acc-bg',
  frequencyText: 'bss-frequency-text pr-7 text-[13px] font-bold text-tp',
  ssoCard: 'bss-sso-card rounded-clausule2 border border-rule-em bg-card p-5',
  ssoRow: 'bss-sso-row flex items-center gap-4',
  ssoAvatar: 'bss-sso-avatar flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-nav text-[13px] font-black text-[#FAF7F3]',
  ssoInfo: 'bss-sso-info min-w-0 flex-1',
  ssoName: 'bss-sso-name text-[14px] font-black text-tp',
  ssoMeta: 'bss-sso-meta mt-1 flex flex-wrap items-center gap-2 text-helper text-tm',
  ssoProvider: 'bss-sso-provider inline-flex items-center gap-2 font-semibold text-tp',
  ssoLogo: 'bss-sso-logo flex h-5 w-5 items-center justify-center',
  ssoStatus: 'bss-sso-status rounded-full bg-[rgba(47,111,94,0.1)] px-3 py-1 text-[11px] font-bold uppercase tracking-[0.08em] text-[#2F6F5E]',
  dangerSection: 'bss-danger-section mt-8',
  dangerLabel: 'bss-danger-label mb-3 text-label font-bold uppercase text-red',
  dangerCard: 'bss-danger-card rounded-clausule2 border border-red/20 bg-red-bg p-5',
  dangerRow: 'bss-danger-row flex flex-wrap items-start justify-between gap-4',
  dangerTitle: 'bss-danger-title text-[15px] font-black text-red',
  dangerDesc: 'bss-danger-desc mt-1 max-w-[34rem] text-helper leading-[1.65] text-[#7D3535]',
  deleteBtn: 'bss-btn-delete rounded-clausule border-none bg-red px-4 py-3 text-[13px] font-bold text-[#FAF7F3] transition-opacity duration-150 hover:opacity-90',
}

export const profileUi = {
  page: 'profile-page max-w-prose',
  card: 'profile-card rounded-clausule2 border border-rule bg-card px-[22px] py-[18px]',
  section: 'profile-section',
  sectionSpacing: 'profile-section mt-5 border-t border-rule pt-5',
  sectionTitle: 'profile-section-title mb-3 text-[9px] font-bold uppercase tracking-[0.08em] text-tm',
  fields: 'profile-fields grid gap-[14px] sm:grid-cols-2',
  field: 'profile-field min-w-0',
  fieldFull: 'profile-field profile-field--full sm:col-span-2',
  label: 'profile-label mb-1.5 block text-helper font-bold text-tp',
  input: 'profile-input block min-h-[42px] w-full rounded-clausule border-[1.5px] border-[rgba(60,45,35,0.12)] bg-transparent px-3 py-2.5 text-[15px] text-tp outline-none transition-[border-color,box-shadow] duration-150 focus:border-tp focus:shadow-[0_0_0_3px_rgba(60,45,35,0.08)]',
  help: 'profile-help mt-2 text-helper leading-[1.6] text-tm',
  alert: 'profile-alert mt-4 rounded-[14px] px-[14px] py-3 text-helper leading-[1.55]',
  alertError: 'profile-alert--error bg-red-bg text-red',
  alertSuccess: 'profile-alert--success bg-[rgba(53,121,73,0.08)] text-[#2f6f43]',
  actions: 'profile-actions mt-5 flex justify-end gap-[10px] border-t border-rule pt-[18px]',
  btn: 'profile-btn rounded-clausule px-4 py-[11px] text-[13px] font-bold transition-[background-color,border-color,opacity,color] duration-150 disabled:cursor-default disabled:opacity-45',
  btnGhost: 'profile-btn--ghost border-[1.5px] border-[rgba(60,45,35,0.14)] bg-transparent text-tm hover:border-[rgba(60,45,35,0.24)] hover:text-tp',
  btnPrimary: 'profile-btn--primary border-none bg-acc text-[#FAF7F3] hover:opacity-90',
  modal: 'profile-modal grid gap-4',
  modalCopy: 'profile-modal-copy text-helper leading-[1.6] text-tm',
  changeList: 'profile-change-list grid gap-x-[14px] gap-y-2 rounded-clausule2 bg-[rgba(60,45,35,0.04)] p-[14px] sm:grid-cols-[auto_1fr]',
  changeTerm: 'text-[11px] font-extrabold uppercase tracking-[0.14em] text-tm',
  changeDesc: 'm-0 text-[12px] font-bold text-tp sm:text-right',
  verify: 'profile-verify grid gap-[10px]',
  verifyTitle: 'profile-verify-title text-[13px] font-extrabold text-tp',
  verifyCopy: 'profile-verify-copy text-helper leading-[1.6] text-tm',
  verifyMeta: 'profile-verify-meta min-h-[18px] text-helper text-tm',
  warning: 'profile-warning grid gap-[10px] rounded-clausule2 bg-[rgba(200,83,42,0.07)] p-[14px]',
  warningStrong: 'profile-warning--strong bg-[rgba(184,50,50,0.1)]',
  warningTitle: 'profile-warning-title text-[13px] font-extrabold text-tp',
  warningCopy: 'text-helper leading-[1.6] text-tp',
  check: 'profile-check flex items-start gap-3 text-helper text-tp',
}
